<?php

namespace Mews\Pos\Tests\DataMapper\ResponseDataMapper;

use Mews\Pos\DataMapper\PayForPosRequestDataMapper;
use Mews\Pos\DataMapper\ResponseDataMapper\PayForPosResponseDataMapper;
use PHPUnit\Framework\TestCase;
use Psr\Log\NullLogger;

class PayForPosResponseDataMapperTest extends TestCase
{
    /** @var PayForPosResponseDataMapper */
    private $responseDataMapper;

    protected function setUp(): void
    {
        parent::setUp();

        $requestDataMapper  = new PayForPosRequestDataMapper();
        $this->responseDataMapper = new PayForPosResponseDataMapper(
            $requestDataMapper->getCurrencyMappings(),
            $requestDataMapper->getTxTypeMappings(),
            new NullLogger()
        );
    }

    /**
     * @dataProvider paymentTestDataProvider
     */
    public function testMapPaymentResponse(array $responseData, array $expectedData)
    {
        $actualData = $this->responseDataMapper->mapPaymentResponse($responseData);
        unset($actualData['all']);
        $this->assertSame($expectedData, $actualData);
    }

    /**
     * @dataProvider threeDPaymentDataProvider
     */
    public function testMap3DPaymentData(array $threeDResponseData, array $paymentResponse, array $expectedData)
    {
        $actualData = $this->responseDataMapper->map3DPaymentData($threeDResponseData, $paymentResponse);
        unset($actualData['all']);
        unset($actualData['3d_all']);
        $this->assertSame($expectedData, $actualData);
    }

    /**
     * @dataProvider threeDPayPaymentDataProvider
     */
    public function testMap3DPayResponseData(array $responseData, array $expectedData)
    {
        $actualData = $this->responseDataMapper->map3DPayResponseData($responseData);
        unset($actualData['all']);
        unset($actualData['3d_all']);
        $this->assertSame($expectedData, $actualData);
    }

    /**
     * @dataProvider threeDHostPaymentDataProvider
     */
    public function testMap3DHostResponseData(array $responseData, array $expectedData)
    {
        $actualData = $this->responseDataMapper->map3DHostResponseData($responseData);
        unset($actualData['all']);
        unset($actualData['3d_all']);
        $this->assertSame($expectedData, $actualData);
    }

    /**
     * @dataProvider statusTestDataProvider
     */
    public function testMapStatusResponse(array $responseData, array $expectedData)
    {
        $actualData = $this->responseDataMapper->mapStatusResponse($responseData);
        unset($actualData['all']);
        $this->assertSame($expectedData, $actualData);
    }

    /**
     * @dataProvider refundTestDataProvider
     */
    public function testMapRefundResponse(array $responseData, array $expectedData)
    {
        $actualData = $this->responseDataMapper->mapRefundResponse($responseData);
        unset($actualData['all']);
        $this->assertSame($expectedData, $actualData);
    }

    /**
     * @dataProvider cancelTestDataProvider
     */
    public function testMapCancelResponse(array $responseData, array $expectedData)
    {
        $actualData = $this->responseDataMapper->mapCancelResponse($responseData);
        unset($actualData['all']);
        $this->assertSame($expectedData, $actualData);
    }

    public function paymentTestDataProvider(): array
    {
        return
            [
                //success case
                [
                    'responseData' => [
                        'AuthCode' => 'S77788',
                        'HostRefNum' => '230422096719',
                        'ProcReturnCode' => '00',
                        'TransId' => '202210313C0D',
                        'ErrMsg' => 'Onaylandı',
                        'CardHolderName' => 'John Doe',
                    ],
                    'expectedData' => [
                        'order_id' => null,
                        'trans_id' => '202210313C0D',
                        'auth_code' => 'S77788',
                        'ref_ret_num' => '230422096719',
                        'proc_return_code' => '00',
                        'status' => 'approved',
                        'status_detail' => 'approved',
                        'error_code' => null,
                        'error_message' => null,
                    ],
                ],
                //fail case
                [
                    'responseData' => [
                        'AuthCode'       => '',
                        'HostRefNum'     => '230422097442',
                        'ProcReturnCode' => 'M041',
                        'TransId'        => '2022103155EF',
                        'ErrMsg'         => 'Geçersiz kart numarası',
                        'CardHolderName' => 'John Doe',
                    ],
                    'expectedData'  => [
                        'order_id' => null,
                        'trans_id' => '2022103155EF',
                        'auth_code' => null,
                        'ref_ret_num' => '230422097442',
                        'proc_return_code' => 'M041',
                        'status' => 'declined',
                        'status_detail' => 'reject',
                        'error_code' => 'M041',
                        'error_message' => 'Geçersiz kart numarası',
                    ],
                ],
                //post fail case
                [
                    'responseData' => [
                        'AuthCode' => '',
                        'HostRefNum' => '230422097825',
                        'ProcReturnCode' => 'V013',
                        'TransId' => '20221031F9FA2',
                        'ErrMsg' => 'Seçili İşlem Bulunamadı!',
                        'CardHolderName' => '',
                    ],
                    'expectedData'  => [
                        'order_id' => null,
                        'trans_id' => '20221031F9FA2',
                        'auth_code' => null,
                        'ref_ret_num' => '230422097825',
                        'proc_return_code' => 'V013',
                        'status' => 'declined',
                        'status_detail' => 'reject',
                        'error_code' => 'V013',
                        'error_message' => 'Seçili İşlem Bulunamadı!',
                    ],
                ],
            ];
    }


    public function threeDPaymentDataProvider(): array
    {
        return [
            [
                // 3D Auth fail case
                'threeDResponseData' => [
                    'RequestGuid' => '1000000081255934',
                    'TransactionDate' => '31.10.2022 22:39:44',
                    'MbrId' => '5',
                    'MerchantID' => '085300000009704',
                    'OrderId' => '202210317565',
                    'RequestIp' => '89.244.149.137',
                    'RequestStat' => '1,4,5',
                    'SecureType' => '3DModel',
                    'PurchAmount' => '1.01',
                    'Exponent' => '2',
                    'Currency' => '949',
                    'Description' => '',
                    'OkUrl' => 'http://localhost/finansbank-payfor/3d/response.php',
                    'FailUrl' => 'http://localhost/finansbank-payfor/3d/response.php',
                    'PayerTxnId' => 'MjAyMjEwMzEyMjM5NDI2MzgwMjg=',
                    'PayerAuthenticationCode' => '',
                    'Eci' => '',
                    'MD' => '',
                    'Hash' => 'Y56v0yOrT+l4fZoRh2wP+nACbwg=',
                    'TerminalID' => 'VS010481',
                    'TxnType' => 'Auth',
                    'OrgOrderId' => '',
                    'SubMerchantCode' => '',
                    'recur_frequency' => '',
                    'recur_expiry' => '',
                    'CardType' => 'V',
                    'Lang' => 'tr',
                    'BonusAmount' => '',
                    'InstallmentCount' => '0',
                    'Rnd' => '97a44150e30c0c202978e7328a5258a3',
                    'AlphaCode' => 'TL',
                    'Ecommerce' => '1',
                    'MrcCountryCode' => '792',
                    'MrcName' => '3D PAY TEST ISYERI',
                    'MerchantHomeUrl' => 'https://vpostest.qnbfinansbank.com/',
                    'CardHolderName' => 'John Doe',
                    'IrcDet' => '3D Secure Authorize Error',
                    'IrcCode' => 'MR15',
                    'Version' => '1.0.2',
                    'TxnStatus' => 'N',
                    'CavvAlg' => '',
                    'ParesVerified' => 'true',
                    'ParesSyntaxOk' => 'false',
                    'ErrMsg' => '3D Kullanıcı Doğrulama Adımı Başarısız',
                    'VendorDet' => '',
                    'D3Stat' => 'N',
                    '3DStatus' => '-1',
                    'TxnResult' => 'Failed',
                    'AuthCode' => '',
                    'HostRefNum' => '',
                    'ProcReturnCode' => 'V034',
                    'ReturnUrl' => 'http://localhost/finansbank-payfor/3d/response.php',
                    'ErrorData' => '',
                    'BatchNo' => '4320',
                    'VoidDate' => '',
                    'CardMask' => '415565******6111',
                    'ReqId' => '26783433',
                    'UsedPoint' => '0',
                    'SrcType' => 'VPO',
                    'RefundedAmount' => '0',
                    'RefundedPoint' => '0',
                    'ReqDate' => '20221031',
                    'SysDate' => '20221031',
                    'F11' => '98691',
                    'F37' => '',
                    'RRN' => '',
                    'IsRepeatTxn' => '',
                    'CavvResult' => '',
                    'VposElapsedTime' => '0',
                    'BankingElapsedTime' => '0',
                    'SocketElapsedTime' => '0',
                    'HsmElapsedTime' => '2',
                    'MpiElapsedTime' => '0',
                    'hasOrderId' => 'False',
                    'TemplateType' => '0',
                    'HasAddressCount' => 'False',
                    'IsPaymentFacilitator' => 'False',
                    'MerchantCountryCode' => '',
                    'OrgTxnType' => '',
                    'F11_ORG' => '0',
                    'F12_ORG' => '0',
                    'F13_ORG' => '',
                    'F22_ORG' => '0',
                    'F25_ORG' => '0',
                    'MTI_ORG' => '0',
                    'DsBrand' => 'V',
                    'IntervalType' => '0',
                    'IntervalDuration' => '0',
                    'RepeatCount' => '0',
                    'CustomerCode' => '',
                    'RequestMerchantDomain' => '',
                    'RequestClientIp' => '89.244.149.137',
                    'ResponseRnd' => 'PF638028527847983529',
                    'ResponseHash' => 'Jzj512Gluz+bmMD8sQYrqCuAQ30=',
                    'BankInternalResponseCode' => '',
                    'BankInternalResponseMessage' => '',
                    'BankInternalResponseSubcode' => '',
                    'BankInternalResponseSubmessage' => '',
                    'BayiKodu' => '',
                    'VoidTime' => '0',
                    'VoidUserCode' => '',
                    'PaymentLinkId' => '0',
                    'ClientId' => '',
                    'IsQRValid' => '',
                    'IsFastValid' => '',
                    'IsQR' => '',
                    'IsFast' => '',
                    'QRRefNo' => '',
                    'FASTGonderenKatilimciKodu' => '',
                    'FASTAlanKatilimciKodu' => '',
                    'FASTReferansNo' => '',
                    'FastGonderenIBAN' => '',
                    'FASTGonderenAdi' => '',
                    'MobileECI' => '',
                    'HubConnId' => '',
                    'WalletData' => '',
                    'Tds2dsTransId' => '',
                    'Is3DHost' => '',
                    'HashType' => 'Sha1',
                ],
                'paymentData'        => [],
                'expectedData'       => [
                    'order_id' => '202210317565',
                    'trans_id' => null,
                    'auth_code' => null,
                    'ref_ret_num' => null,
                    'proc_return_code' => 'V034',
                    'status' => 'declined',
                    'status_detail' => 'try_again',
                    'error_code' => 'V034',
                    'error_message' => '3D Kullanıcı Doğrulama Adımı Başarısız',
                    'transaction_type' => 'Auth',
                    'transaction_security' => '3DModel',
                    'masked_number' => '415565******6111',
                    'amount' => 1.01,
                    'currency' => 'TRY',
                    'tx_status' => 'Failed',
                    'md_status' => '-1',
                    'md_error_code' => 'V034',
                    'md_error_message' => '3D Kullanıcı Doğrulama Adımı Başarısız',
                    'md_status_detail' => 'try_again',
                    'eci' => null,
                ],
            ],
            [
                // Success case
                'threeDResponseData' => [
                    'RequestGuid' => '1000000081255931',
                    'TransactionDate' => '31.10.2022 22:34:18',
                    'MbrId' => '5',
                    'MerchantID' => '085300000009704',
                    'OrderId' => '20221031CFD0',
                    'RequestIp' => '89.244.149.137',
                    'RequestStat' => '1,3,5',
                    'SecureType' => '3DModel',
                    'PurchAmount' => '1.01',
                    'Exponent' => '2',
                    'Currency' => '949',
                    'Description' => '',
                    'OkUrl' => 'http://localhost/finansbank-payfor/3d/response.php',
                    'FailUrl' => 'http://localhost/finansbank-payfor/3d/response.php',
                    'PayerTxnId' => 'MjAyMjEwMzEyMjM0MTM2MzgwMjg=',
                    'PayerAuthenticationCode' => 'AAABBCaIaIAoUkWEBYhoAAAAAAA=',
                    'Eci' => '05',
                    'MD' => '',
                    'Hash' => 'KuJcFyXYZcW8NetghUN7uBgzQPE=',
                    'TerminalID' => 'VS010481',
                    'TxnType' => 'Auth',
                    'OrgOrderId' => '',
                    'SubMerchantCode' => '',
                    'recur_frequency' => '',
                    'recur_expiry' => '',
                    'CardType' => 'V',
                    'Lang' => 'tr',
                    'BonusAmount' => '',
                    'InstallmentCount' => '0',
                    'Rnd' => '94381aefb4b8865c54cce0a1f1c74f12',
                    'AlphaCode' => 'TL',
                    'Ecommerce' => '1',
                    'MrcCountryCode' => '792',
                    'MrcName' => '3D PAY TEST ISYERI',
                    'MerchantHomeUrl' => 'https://vpostest.qnbfinansbank.com/',
                    'CardHolderName' => 'John Doe',
                    'IrcDet' => '',
                    'IrcCode' => '',
                    'Version' => '1.0.2',
                    'TxnStatus' => 'N',
                    'CavvAlg' => '2',
                    'ParesVerified' => 'true',
                    'ParesSyntaxOk' => 'true',
                    'ErrMsg' => '3D Kullanıcı Doğrulama Adımı Başarılı',
                    'VendorDet' => '',
                    'D3Stat' => 'Y',
                    '3DStatus' => '1',
                    'TxnResult' => 'Failed',
                    'AuthCode' => '',
                    'HostRefNum' => '',
                    'ProcReturnCode' => 'V033',
                    'ReturnUrl' => 'http://localhost/finansbank-payfor/3d/response.php',
                    'ErrorData' => '',
                    'BatchNo' => '4320',
                    'VoidDate' => '',
                    'CardMask' => '415565******6111',
                    'ReqId' => '26782891',
                    'UsedPoint' => '0',
                    'SrcType' => 'VPO',
                    'RefundedAmount' => '0',
                    'RefundedPoint' => '0',
                    'ReqDate' => '20221031',
                    'SysDate' => '20221031',
                    'F11' => '98249',
                    'F37' => '',
                    'RRN' => '',
                    'IsRepeatTxn' => '',
                    'CavvResult' => '',
                    'VposElapsedTime' => '0',
                    'BankingElapsedTime' => '0',
                    'SocketElapsedTime' => '0',
                    'HsmElapsedTime' => '2',
                    'MpiElapsedTime' => '0',
                    'hasOrderId' => 'False',
                    'TemplateType' => '0',
                    'HasAddressCount' => 'False',
                    'IsPaymentFacilitator' => 'False',
                    'MerchantCountryCode' => '',
                    'OrgTxnType' => '',
                    'F11_ORG' => '0',
                    'F12_ORG' => '0',
                    'F13_ORG' => '',
                    'F22_ORG' => '0',
                    'F25_ORG' => '0',
                    'MTI_ORG' => '0',
                    'DsBrand' => 'V',
                    'IntervalType' => '0',
                    'IntervalDuration' => '0',
                    'RepeatCount' => '0',
                    'CustomerCode' => '',
                    'RequestMerchantDomain' => '',
                    'RequestClientIp' => '89.244.149.137',
                    'ResponseRnd' => 'PF638028524588902912',
                    'ResponseHash' => '6OWhNzqTEXUGkY6HN90QKHdP53c=',
                    'BankInternalResponseCode' => '',
                    'BankInternalResponseMessage' => '',
                    'BankInternalResponseSubcode' => '',
                    'BankInternalResponseSubmessage' => '',
                    'BayiKodu' => '',
                    'VoidTime' => '0',
                    'VoidUserCode' => '',
                    'PaymentLinkId' => '0',
                    'ClientId' => '',
                    'IsQRValid' => '',
                    'IsFastValid' => '',
                    'IsQR' => '',
                    'IsFast' => '',
                    'QRRefNo' => '',
                    'FASTGonderenKatilimciKodu' => '',
                    'FASTAlanKatilimciKodu' => '',
                    'FASTReferansNo' => '',
                    'FastGonderenIBAN' => '',
                    'FASTGonderenAdi' => '',
                    'MobileECI' => '',
                    'HubConnId' => '',
                    'WalletData' => '',
                    'Tds2dsTransId' => '',
                    'Is3DHost' => '',
                    'HashType' => 'Sha1',
                ],
                'paymentData'        => [
                    'AuthCode' => 'S37397',
                    'HostRefNum' => '230422098249',
                    'ProcReturnCode' => '00',
                    'TransId' => '20221031CFD0',
                    'ErrMsg' => 'Onaylandı',
                    'CardHolderName' => 'John Doe',
                ],
                'expectedData'       => [
                    'transaction_type' => 'Auth',
                    'transaction_security' => '3DModel',
                    'masked_number' => '415565******6111',
                    'amount' => 1.01,
                    'currency' => 'TRY',
                    'tx_status' => 'Failed',
                    'md_status' => '1',
                    'md_error_code' => null,
                    'md_error_message' => null,
                    'md_status_detail' => null,
                    'eci' => '05',
                    'trans_id' => '20221031CFD0',
                    'auth_code' => 'S37397',
                    'ref_ret_num' => '230422098249',
                    'order_id' => '20221031CFD0',
                    'proc_return_code' => '00',
                    'status' => 'approved',
                    'status_detail' => 'approved',
                    'error_code' => null,
                    'error_message' => null,
                ],
            ],
        ];
    }


    public function threeDPayPaymentDataProvider(): array
    {
        return [
            'success1' => [
                'paymentData'  => [
                    'RequestGuid' => '1000000081255944',
                    'TransactionDate' => '31.10.2022 22:56:43',
                    'MbrId' => '5',
                    'MerchantID' => '085300000009704',
                    'OrderId' => '2022103114B3',
                    'RequestIp' => '89.244.149.137',
                    'RequestStat' => '1,3,10,5',
                    'SecureType' => '3DPay',
                    'PurchAmount' => '1.01',
                    'Exponent' => '2',
                    'Currency' => '949',
                    'Description' => '',
                    'OkUrl' => 'http://localhost/finansbank-payfor/3d-pay/response.php',
                    'FailUrl' => 'http://localhost/finansbank-payfor/3d-pay/response.php',
                    'PayerTxnId' => 'MjAyMjEwMzEyMjU2Mzg2MzgwMjg=',
                    'PayerAuthenticationCode' => 'AAABASI0Q4AoU4AomDRDAAAAAAA=',
                    'Eci' => '05',
                    'MD' => '',
                    'Hash' => 'lzsn2UeZpuOabSYTwbVfixk0tbg=',
                    'TerminalID' => 'VS010481',
                    'TxnType' => 'Auth',
                    'OrgOrderId' => '',
                    'SubMerchantCode' => '',
                    'recur_frequency' => '',
                    'recur_expiry' => '',
                    'CardType' => 'V',
                    'Lang' => 'tr',
                    'BonusAmount' => '',
                    'InstallmentCount' => '2',
                    'Rnd' => 'aff83bea26a1d13a0976f9cb6c14ee27',
                    'AlphaCode' => 'TL',
                    'Ecommerce' => '1',
                    'MrcCountryCode' => '792',
                    'MrcName' => '3D PAY TEST ISYERI',
                    'MerchantHomeUrl' => 'https://vpostest.qnbfinansbank.com/',
                    'CardHolderName' => 'John Doe',
                    'IrcDet' => '',
                    'IrcCode' => '',
                    'Version' => '1.0.2',
                    'TxnStatus' => 'Y',
                    'CavvAlg' => '2',
                    'ParesVerified' => 'true',
                    'ParesSyntaxOk' => 'true',
                    'ErrMsg' => 'Onaylandı',
                    'VendorDet' => '',
                    'D3Stat' => 'Y',
                    '3DStatus' => '1',
                    'TxnResult' => 'Success',
                    'AuthCode' => 'S86797',
                    'HostRefNum' => '230422100150',
                    'ProcReturnCode' => '00',
                    'ReturnUrl' => 'http://localhost/finansbank-payfor/3d-pay/response.php',
                    'ErrorData' => '',
                    'BatchNo' => '4320',
                    'VoidDate' => '',
                    'CardMask' => '415565******6111',
                    'ReqId' => '26784792',
                    'UsedPoint' => '0',
                    'SrcType' => 'VPO',
                    'RefundedAmount' => '0',
                    'RefundedPoint' => '0',
                    'ReqDate' => '20221031',
                    'SysDate' => '20221031',
                    'F11' => '100150',
                    'F37' => '230422100150',
                    'RRN' => '230422100150',
                    'IsRepeatTxn' => '',
                    'CavvResult' => '',
                    'VposElapsedTime' => '254',
                    'BankingElapsedTime' => '0',
                    'SocketElapsedTime' => '0',
                    'HsmElapsedTime' => '4',
                    'MpiElapsedTime' => '4977',
                    'hasOrderId' => 'False',
                    'TemplateType' => '0',
                    'HasAddressCount' => 'False',
                    'IsPaymentFacilitator' => 'False',
                    'MerchantCountryCode' => 'TR',
                    'OrgTxnType' => '',
                    'F11_ORG' => '0',
                    'F12_ORG' => '0',
                    'F13_ORG' => '',
                    'F22_ORG' => '0',
                    'F25_ORG' => '0',
                    'MTI_ORG' => '0',
                    'DsBrand' => 'V',
                    'IntervalType' => '0',
                    'IntervalDuration' => '0',
                    'RepeatCount' => '0',
                    'CustomerCode' => '',
                    'RequestMerchantDomain' => '',
                    'RequestClientIp' => '89.244.149.137',
                    'ResponseRnd' => 'PF638028538035077529',
                    'ResponseHash' => 'il/SWNG2llQkLgnCbUG6lPYtlgM=',
                    'BankInternalResponseCode' => '',
                    'BankInternalResponseMessage' => '',
                    'BankInternalResponseSubcode' => '',
                    'BankInternalResponseSubmessage' => '',
                    'BayiKodu' => '',
                    'VoidTime' => '0',
                    'VoidUserCode' => '',
                    'PaymentLinkId' => '0',
                    'ClientId' => '',
                    'IsQRValid' => '',
                    'IsFastValid' => '',
                    'IsQR' => '',
                    'IsFast' => '',
                    'QRRefNo' => '',
                    'FASTGonderenKatilimciKodu' => '',
                    'FASTAlanKatilimciKodu' => '',
                    'FASTReferansNo' => '',
                    'FastGonderenIBAN' => '',
                    'FASTGonderenAdi' => '',
                    'MobileECI' => '',
                    'HubConnId' => '',
                    'WalletData' => '',
                    'Tds2dsTransId' => '',
                    'Is3DHost' => '',
                    'HashType' => 'Sha1',
                ],
                'expectedData' => [
                    'trans_id' => null,
                    'auth_code' => 'S86797',
                    'ref_ret_num' => '230422100150',
                    'order_id' => '2022103114B3',
                    'transaction_type' => 'Auth',
                    'proc_return_code' => '00',
                    'status' => 'approved',
                    'status_detail' => 'approved',
                    'error_code' => null,
                    'error_message' => null,
                    'transaction_security' => '3DPay',
                    'masked_number' => '415565******6111',
                    'amount' => 1.01,
                    'currency' => 'TRY',
                    'tx_status' => 'Success',
                    'md_status' => '1',
                    'md_error_code' => null,
                    'md_error_message' => null,
                    'md_status_detail' => 'approved',
                    'eci' => '05',
                ],
            ],
            'authFail1' => [
                'paymentData'  => [
                    'RequestGuid' => '1000000081255948',
                    'TransactionDate' => '31.10.2022 23:01:36',
                    'MbrId' => '5',
                    'MerchantID' => '085300000009704',
                    'OrderId' => '202210317223',
                    'RequestIp' => '89.244.149.137',
                    'RequestStat' => '1,4,5',
                    'SecureType' => '3DPay',
                    'PurchAmount' => '1.01',
                    'Exponent' => '2',
                    'Currency' => '949',
                    'Description' => '',
                    'OkUrl' => 'http://localhost/finansbank-payfor/3d-pay/response.php',
                    'FailUrl' => 'http://localhost/finansbank-payfor/3d-pay/response.php',
                    'PayerTxnId' => 'MjAyMjEwMzEyMzAxMzI2MzgwMjg=',
                    'PayerAuthenticationCode' => '',
                    'Eci' => '',
                    'MD' => '',
                    'Hash' => 'VbadsdpyAqh56fzNOC3ewhFXrHY=',
                    'TerminalID' => 'VS010481',
                    'TxnType' => 'Auth',
                    'OrgOrderId' => '',
                    'SubMerchantCode' => '',
                    'recur_frequency' => '',
                    'recur_expiry' => '',
                    'CardType' => 'V',
                    'Lang' => 'tr',
                    'BonusAmount' => '',
                    'InstallmentCount' => '0',
                    'Rnd' => '206e224bf1ddc63edc7c5f5b519f9f0a',
                    'AlphaCode' => 'TL',
                    'Ecommerce' => '1',
                    'MrcCountryCode' => '792',
                    'MrcName' => '3D PAY TEST ISYERI',
                    'MerchantHomeUrl' => 'https://vpostest.qnbfinansbank.com/',
                    'CardHolderName' => 'John Doe',
                    'IrcDet' => '3D Secure Authorize Error',
                    'IrcCode' => 'MR15',
                    'Version' => '1.0.2',
                    'TxnStatus' => 'N',
                    'CavvAlg' => '',
                    'ParesVerified' => 'true',
                    'ParesSyntaxOk' => 'false',
                    'ErrMsg' => '3D Secure Authorize Error',
                    'VendorDet' => '',
                    'D3Stat' => 'N',
                    '3DStatus' => '-1',
                    'TxnResult' => 'Failed',
                    'AuthCode' => '',
                    'HostRefNum' => '',
                    'ProcReturnCode' => 'MR15',
                    'ReturnUrl' => 'http://localhost/finansbank-payfor/3d-pay/response.php',
                    'ErrorData' => '',
                    'BatchNo' => '4320',
                    'VoidDate' => '',
                    'CardMask' => '415565******6111',
                    'ReqId' => '26785209',
                    'UsedPoint' => '0',
                    'SrcType' => 'VPO',
                    'RefundedAmount' => '0',
                    'RefundedPoint' => '0',
                    'ReqDate' => '20221031',
                    'SysDate' => '20221031',
                    'F11' => '100567',
                    'F37' => '',
                    'RRN' => '',
                    'IsRepeatTxn' => '',
                    'CavvResult' => '',
                    'VposElapsedTime' => '0',
                    'BankingElapsedTime' => '0',
                    'SocketElapsedTime' => '0',
                    'HsmElapsedTime' => '2',
                    'MpiElapsedTime' => '0',
                    'hasOrderId' => 'False',
                    'TemplateType' => '0',
                    'HasAddressCount' => 'False',
                    'IsPaymentFacilitator' => 'False',
                    'MerchantCountryCode' => '',
                    'OrgTxnType' => '',
                    'F11_ORG' => '0',
                    'F12_ORG' => '0',
                    'F13_ORG' => '',
                    'F22_ORG' => '0',
                    'F25_ORG' => '0',
                    'MTI_ORG' => '0',
                    'DsBrand' => 'V',
                    'IntervalType' => '0',
                    'IntervalDuration' => '0',
                    'RepeatCount' => '0',
                    'CustomerCode' => '',
                    'RequestMerchantDomain' => '',
                    'RequestClientIp' => '89.244.149.137',
                    'ResponseRnd' => 'PF638028540963074026',
                    'ResponseHash' => 'n3zpDnIyZcVRGVowGNuMK4rH3x4=',
                    'BankInternalResponseCode' => '',
                    'BankInternalResponseMessage' => '',
                    'BankInternalResponseSubcode' => '',
                    'BankInternalResponseSubmessage' => '',
                    'BayiKodu' => '',
                    'VoidTime' => '0',
                    'VoidUserCode' => '',
                    'PaymentLinkId' => '0',
                    'ClientId' => '',
                    'IsQRValid' => '',
                    'IsFastValid' => '',
                    'IsQR' => '',
                    'IsFast' => '',
                    'QRRefNo' => '',
                    'FASTGonderenKatilimciKodu' => '',
                    'FASTAlanKatilimciKodu' => '',
                    'FASTReferansNo' => '',
                    'FastGonderenIBAN' => '',
                    'FASTGonderenAdi' => '',
                    'MobileECI' => '',
                    'HubConnId' => '',
                    'WalletData' => '',
                    'Tds2dsTransId' => '',
                    'Is3DHost' => '',
                    'HashType' => 'Sha1',
                ],
                'expectedData' => [
                    'trans_id' => null,
                    'auth_code' => null,
                    'ref_ret_num' => null,
                    'order_id' => '202210317223',
                    'transaction_type' => 'Auth',
                    'proc_return_code' => 'MR15',
                    'status' => 'declined',
                    'status_detail' => 'try_again',
                    'error_code' => 'MR15',
                    'error_message' => '3D Secure Authorize Error',
                    'transaction_security' => '3DPay',
                    'masked_number' => '415565******6111',
                    'amount' => 1.01,
                    'currency' => 'TRY',
                    'tx_status' => 'Failed',
                    'md_status' => '-1',
                    'md_error_code' => 'MR15',
                    'md_error_message' => '3D Secure Authorize Error',
                    'md_status_detail' => 'try_again',
                    'eci' => null,
                ],
            ],
        ];
    }


    public function threeDHostPaymentDataProvider(): array
    {
        return [
            'success1' => [
                // success case
                'paymentData'  => [
                    'RequestGuid' => '1000000081265956',
                    'TransactionDate' => '31.10.2022 23:06:37',
                    'MbrId' => '5',
                    'MerchantID' => '085300000009704',
                    'OrderId' => '2022103121CA',
                    'RequestIp' => '89.244.149.137',
                    'RequestStat' => '1,2,3,10,5',
                    'SecureType' => '3DHost',
                    'PurchAmount' => '1.01',
                    'Exponent' => '2',
                    'Currency' => '949',
                    'Description' => '',
                    'OkUrl' => 'http://localhost/finansbank-payfor/3d-host/response.php',
                    'FailUrl' => 'http://localhost/finansbank-payfor/3d-host/response.php',
                    'PayerTxnId' => 'MjAyMjEwMzEyMzA2MzI2MzgwMjg=',
                    'PayerAuthenticationCode' => 'AAABBFJnWIAoVDljkGdYAAAAAAA=',
                    'Eci' => '05',
                    'MD' => '',
                    'Hash' => '7FYgYx1LMSNT8DaZx4yc4GqSdDA=',
                    'TerminalID' => 'VS010481',
                    'TxnType' => 'Auth',
                    'OrgOrderId' => '',
                    'SubMerchantCode' => '',
                    'recur_frequency' => '',
                    'recur_expiry' => '',
                    'CardType' => 'V',
                    'Lang' => 'tr',
                    'BonusAmount' => '',
                    'InstallmentCount' => '3',
                    'Rnd' => '9e7a88deaf70a148fd40551d69503ba1',
                    'AlphaCode' => 'TL',
                    'Ecommerce' => '1',
                    'MrcCountryCode' => '792',
                    'MrcName' => '3D PAY TEST ISYERI',
                    'MerchantHomeUrl' => 'https://vpostest.qnbfinansbank.com/',
                    'CardHolderName' => 'JOHN DOE',
                    'IrcDet' => '',
                    'IrcCode' => '',
                    'Version' => '1.0.2',
                    'TxnStatus' => 'Y',
                    'CavvAlg' => '2',
                    'ParesVerified' => 'true',
                    'ParesSyntaxOk' => 'true',
                    'ErrMsg' => 'Onaylandı',
                    'VendorDet' => '',
                    'D3Stat' => 'Y',
                    '3DStatus' => '1',
                    'TxnResult' => 'Success',
                    'AuthCode' => 'S28031',
                    'HostRefNum' => '230423100695',
                    'ProcReturnCode' => '00',
                    'ReturnUrl' => 'http://localhost/finansbank-payfor/3d-host/response.php',
                    'ErrorData' => '',
                    'BatchNo' => '4320',
                    'VoidDate' => '',
                    'CardMask' => '415565******6111',
                    'ReqId' => '26785344',
                    'UsedPoint' => '0',
                    'SrcType' => 'VPO',
                    'RefundedAmount' => '0',
                    'RefundedPoint' => '0',
                    'ReqDate' => '20221031',
                    'SysDate' => '20221031',
                    'F11' => '100695',
                    'F37' => '230423100695',
                    'RRN' => '230423100695',
                    'IsRepeatTxn' => '',
                    'CavvResult' => '',
                    'VposElapsedTime' => '24256',
                    'BankingElapsedTime' => '0',
                    'SocketElapsedTime' => '0',
                    'HsmElapsedTime' => '4',
                    'MpiElapsedTime' => '4422',
                    'hasOrderId' => 'False',
                    'TemplateType' => '0',
                    'HasAddressCount' => 'False',
                    'IsPaymentFacilitator' => 'False',
                    'MerchantCountryCode' => 'TR',
                    'OrgTxnType' => '',
                    'F11_ORG' => '0',
                    'F12_ORG' => '0',
                    'F13_ORG' => '',
                    'F22_ORG' => '0',
                    'F25_ORG' => '0',
                    'MTI_ORG' => '0',
                    'DsBrand' => 'V',
                    'IntervalType' => '0',
                    'IntervalDuration' => '0',
                    'RepeatCount' => '0',
                    'CustomerCode' => '',
                    'RequestMerchantDomain' => '',
                    'RequestClientIp' => '89.244.149.137',
                    'ResponseRnd' => 'PF638028543970517651',
                    'ResponseHash' => 'R3sOuVFWDP8nvu9mtVtvLxwlqow=',
                    'BankInternalResponseCode' => '',
                    'BankInternalResponseMessage' => '',
                    'BankInternalResponseSubcode' => '',
                    'BankInternalResponseSubmessage' => '',
                    'BayiKodu' => '',
                    'VoidTime' => '0',
                    'VoidUserCode' => '',
                    'PaymentLinkId' => '0',
                    'ClientId' => '',
                    'IsQRValid' => '',
                    'IsFastValid' => '',
                    'IsQR' => '',
                    'IsFast' => '',
                    'QRRefNo' => '',
                    'FASTGonderenKatilimciKodu' => '',
                    'FASTAlanKatilimciKodu' => '',
                    'FASTReferansNo' => '',
                    'FastGonderenIBAN' => '',
                    'FASTGonderenAdi' => '',
                    'MobileECI' => '',
                    'HubConnId' => '',
                    'WalletData' => '',
                    'Tds2dsTransId' => '',
                    'Is3DHost' => '',
                    'HashType' => 'Sha1',
                ],
                'expectedData' => [
                    'trans_id' => null,
                    'auth_code' => 'S28031',
                    'ref_ret_num' => '230423100695',
                    'order_id' => '2022103121CA',
                    'transaction_type' => 'Auth',
                    'proc_return_code' => '00',
                    'status' => 'approved',
                    'status_detail' => 'approved',
                    'error_code' => null,
                    'error_message' => null,
                    'transaction_security' => '3DHost',
                    'masked_number' => '415565******6111',
                    'amount' => 1.01,
                    'currency' => 'TRY',
                    'tx_status' => 'Success',
                    'md_status' => '1',
                    'md_error_code' => null,
                    'md_error_message' => null,
                    'md_status_detail' => 'approved',
                    'eci' => '05',
                ],
            ],
            [
                //  3d fail case
                'paymentData'  => [
                    'RequestGuid' => '1000000081265960',
                    'TransactionDate' => '31.10.2022 23:10:47',
                    'MbrId' => '5',
                    'MerchantID' => '085300000009704',
                    'OrderId' => '202210316DBA',
                    'RequestIp' => '89.244.149.137',
                    'RequestStat' => '1,2,4,5',
                    'SecureType' => '3DHost',
                    'PurchAmount' => '1.01',
                    'Exponent' => '2',
                    'Currency' => '949',
                    'Description' => '',
                    'OkUrl' => 'http://localhost/finansbank-payfor/3d-host/response.php',
                    'FailUrl' => 'http://localhost/finansbank-payfor/3d-host/response.php',
                    'PayerTxnId' => 'MjAyMjEwMzEyMzEwNDU2MzgwMjg=',
                    'PayerAuthenticationCode' => '',
                    'Eci' => '',
                    'MD' => '',
                    'Hash' => 'njYhnUb4hEFmsMav7Z+QqG+91/U=',
                    'TerminalID' => 'VS010481',
                    'TxnType' => 'Auth',
                    'OrgOrderId' => '',
                    'SubMerchantCode' => '',
                    'recur_frequency' => '',
                    'recur_expiry' => '',
                    'CardType' => 'V',
                    'Lang' => 'tr',
                    'BonusAmount' => '',
                    'InstallmentCount' => '3',
                    'Rnd' => '5fc1f8b2b3fd0b28959548f0951587e7',
                    'AlphaCode' => 'TL',
                    'Ecommerce' => '1',
                    'MrcCountryCode' => '792',
                    'MrcName' => '3D PAY TEST ISYERI',
                    'MerchantHomeUrl' => 'https://vpostest.qnbfinansbank.com/',
                    'CardHolderName' => 'JOHN DOE',
                    'IrcDet' => '3D Secure Authorize Error',
                    'IrcCode' => 'MR15',
                    'Version' => '1.0.2',
                    'TxnStatus' => 'P',
                    'CavvAlg' => '',
                    'ParesVerified' => 'true',
                    'ParesSyntaxOk' => 'false',
                    'ErrMsg' => '3D Secure Authorize Error',
                    'VendorDet' => '',
                    'D3Stat' => 'N',
                    '3DStatus' => '-1',
                    'TxnResult' => 'Failed',
                    'AuthCode' => '',
                    'HostRefNum' => '',
                    'ProcReturnCode' => 'MR15',
                    'ReturnUrl' => 'http://localhost/finansbank-payfor/3d-host/response.php',
                    'ErrorData' => '',
                    'BatchNo' => '4320',
                    'VoidDate' => '',
                    'CardMask' => '415565******6111',
                    'ReqId' => '26785969',
                    'UsedPoint' => '0',
                    'SrcType' => 'VPO',
                    'RefundedAmount' => '0',
                    'RefundedPoint' => '0',
                    'ReqDate' => '20221031',
                    'SysDate' => '20221031',
                    'F11' => '101327',
                    'F37' => '',
                    'RRN' => '',
                    'IsRepeatTxn' => '',
                    'CavvResult' => '',
                    'VposElapsedTime' => '18767',
                    'BankingElapsedTime' => '0',
                    'SocketElapsedTime' => '0',
                    'HsmElapsedTime' => '2',
                    'MpiElapsedTime' => '0',
                    'hasOrderId' => 'False',
                    'TemplateType' => '0',
                    'HasAddressCount' => 'False',
                    'IsPaymentFacilitator' => 'False',
                    'MerchantCountryCode' => '',
                    'OrgTxnType' => '',
                    'F11_ORG' => '0',
                    'F12_ORG' => '0',
                    'F13_ORG' => '',
                    'F22_ORG' => '0',
                    'F25_ORG' => '0',
                    'MTI_ORG' => '0',
                    'DsBrand' => 'V',
                    'IntervalType' => '0',
                    'IntervalDuration' => '0',
                    'RepeatCount' => '0',
                    'CustomerCode' => '',
                    'RequestMerchantDomain' => '',
                    'RequestClientIp' => '89.244.149.137',
                    'ResponseRnd' => 'PF638028546475263865',
                    'ResponseHash' => '7wnXcENucbamQSSzh95kRA8nzN8=',
                    'BankInternalResponseCode' => '',
                    'BankInternalResponseMessage' => '',
                    'BankInternalResponseSubcode' => '',
                    'BankInternalResponseSubmessage' => '',
                    'BayiKodu' => '',
                    'VoidTime' => '0',
                    'VoidUserCode' => '',
                    'PaymentLinkId' => '0',
                    'ClientId' => '',
                    'IsQRValid' => '',
                    'IsFastValid' => '',
                    'IsQR' => '',
                    'IsFast' => '',
                    'QRRefNo' => '',
                    'FASTGonderenKatilimciKodu' => '',
                    'FASTAlanKatilimciKodu' => '',
                    'FASTReferansNo' => '',
                    'FastGonderenIBAN' => '',
                    'FASTGonderenAdi' => '',
                    'MobileECI' => '',
                    'HubConnId' => '',
                    'WalletData' => '',
                    'Tds2dsTransId' => '',
                    'Is3DHost' => '',
                    'HashType' => 'Sha1',
                ],
                'expectedData' => [
                    'trans_id' => null,
                    'auth_code' => null,
                    'ref_ret_num' => null,
                    'order_id' => '202210316DBA',
                    'transaction_type' => 'Auth',
                    'proc_return_code' => 'MR15',
                    'status' => 'declined',
                    'status_detail' => 'try_again',
                    'error_code' => 'MR15',
                    'error_message' => '3D Secure Authorize Error',
                    'transaction_security' => '3DHost',
                    'masked_number' => '415565******6111',
                    'amount' => 1.01,
                    'currency' => 'TRY',
                    'tx_status' => 'Failed',
                    'md_status' => '-1',
                    'md_error_code' => 'MR15',
                    'md_error_message' => '3D Secure Authorize Error',
                    'md_status_detail' => 'try_again',
                    'eci' => null,
                ],
            ],
        ];
    }


    public function statusTestDataProvider(): array
    {
        return
            [
                'success1' => [
                    'responseData' => [
                        'RequestGuid' => '1000000081265961',
                        'InsertDatetime' => '31.10.2022 23:13:21',
                        'MbrId' => '5',
                        'MerchantID' => '085300000009704',
                        'OrderId' => '202210312A24',
                        'RequestIp' => '89.244.149.137',
                        'RequestStat' => '1,10',
                        'SecureType' => 'NonSecure',
                        'PurchAmount' => '1.01',
                        'Exponent' => '2',
                        'Currency' => '949',
                        'Description' => '',
                        'OkUrl' => '',
                        'FailUrl' => '',
                        'PayerTxnId' => '',
                        'PayerAuthenticationCode' => '',
                        'Eci' => '',
                        'MD' => '',
                        'Hash' => '',
                        'TerminalID' => 'VS010481',
                        'TxnType' => 'Auth',
                        'OrgOrderId' => '',
                        'SubMerchantCode' => '',
                        'recur_frequency' => '',
                        'recur_expiry' => '',
                        'CardType' => 'V',
                        'Lang' => 'tr',
                        'BonusAmount' => '',
                        'InstallmentCount' => '0',
                        'Rnd' => '',
                        'AlphaCode' => 'TL',
                        'Ecommerce' => '1',
                        'MrcCountryCode' => '792',
                        'MrcName' => '3D PAY TEST ISYERI',
                        'MerchantHomeUrl' => 'https://vpostest.qnbfinansbank.com/',
                        'CardHolderName' => 'John Doe',
                        'IrcDet' => '',
                        'IrcCode' => '',
                        'Version' => '',
                        'TxnStatus' => 'Y',
                        'CavvAlg' => '',
                        'ParesVerified' => '',
                        'ParesSyntaxOk' => '',
                        'ErrMsg' => 'Onaylandı',
                        'VendorDet' => '',
                        'D3Status' => '-1',
                        'TxnResult' => 'Success',
                        'AuthCode' => 'S90370',
                        'HostRefNum' => '',
                        'ProcReturnCode' => '00',
                        'ReturnUrl' => '',
                        'ErrorData' => '',
                        'BatchNo' => '4320',
                        'VoidDate' => '',
                        'CardMask' => '415565******6111',
                        'ReqId' => '26786247',
                        'UsedPoint' => '0',
                        'SrcType' => 'VPO',
                        'RefundedAmount' => '0',
                        'RefundedPoint' => '0',
                        'ReqDate' => '20221031',
                        'SysDate' => '20221031',
                        'F11' => '101605',
                        'F37' => '230423101605',
                        'IsRepeatTxn' => '',
                        'CavvResult' => '',
                        'VposElapsedTime' => '16',
                        'BankingElapsedTime' => '0',
                        'SocketElapsedTime' => '0',
                        'HsmElapsedTime' => '5',
                        'MpiElapsedTime' => '0',
                        'hasOrderId' => 'False',
                        'TemplateType' => '0',
                        'HasAddressCount' => 'False',
                        'IsPaymentFacilitator' => 'False',
                        'MerchantCountryCode' => '',
                        'OrgTxnType' => '',
                        'F11_ORG' => '0',
                        'F12_ORG' => '0',
                        'F13_ORG' => '',
                        'F22_ORG' => '0',
                        'F25_ORG' => '0',
                        'MTI_ORG' => '0',
                        'DsBrand' => '',
                        'IntervalType' => '0',
                        'IntervalDuration' => '0',
                        'RepeatCount' => '0',
                        'CustomerCode' => '',
                        'RequestMerchantDomain' => '',
                        'RequestClientIp' => '89.244.149.137',
                        'ResponseRnd' => '',
                        'ResponseHash' => '',
                        'BankInternalResponseCode' => '',
                        'BankInternalResponseMessage' => '',
                        'BankInternalResponseSubcode' => '',
                        'BankInternalResponseSubmessage' => '',
                        'BayiKodu' => '',
                        'VoidTime' => '0',
                        'VoidUserCode' => '',
                        'PaymentLinkId' => '0',
                        'ClientId' => '',
                        'IsQRValid' => '',
                        'IsFastValid' => '',
                        'IsQR' => '',
                        'IsFast' => '',
                        'QRRefNo' => '',
                        'FASTGonderenKatilimciKodu' => '',
                        'FASTAlanKatilimciKodu' => '',
                        'FASTReferansNo' => '',
                        'FastGonderenIBAN' => '',
                        'FASTGonderenAdi' => '',
                        'MobileECI' => '',
                        'HubConnId' => '',
                        'WalletData' => '',
                        'Tds2dsTransId' => '',
                        'Is3DHost' => '',
                        'PAYFORFROMXMLREQUEST' => '1',
                        'IsVoided' => 'false',
                        'IsRefunded' => 'false',
                        'TrxDate' => '31.10.2022 23:13',
                        'ReturnMessage' => 'Onaylandı',
                    ],
                    'expectedData' => [
                        'auth_code' => 'S90370',
                        'order_id' => '202210312A24',
                        'org_order_id' => null,
                        'proc_return_code' => '00',
                        'error_message' => null,
                        'ref_ret_num' => null,
                        'order_status' => 'approved',
                        'transaction_type' => 'pay',
                        'masked_number' => '415565******6111',
                        'amount' => 1.01,
                        'currency' => 'TRY',
                        'status' => 'approved',
                        'status_detail' => 'approved',
                    ],
                ],
                'fail1' => [
                    'responseData' => [
                        'RequestGuid' => '0',
                        'InsertDatetime' => '1.01.0001 00:00:00',
                        'MbrId' => '5',
                        'MerchantID' => '085300000009704',
                        'OrderId' => '202210312A242',
                        'RequestIp' => '89.244.149.137',
                        'RequestStat' => '1,10',
                        'SecureType' => 'Inquiry',
                        'PurchAmount' => '',
                        'Exponent' => '2',
                        'Currency' => '949',
                        'Description' => '',
                        'OkUrl' => '',
                        'FailUrl' => '',
                        'PayerTxnId' => '',
                        'PayerAuthenticationCode' => '',
                        'Eci' => '',
                        'MD' => '',
                        'Hash' => '',
                        'TerminalID' => 'VS010481',
                        'TxnType' => 'OrderInquiry',
                        'OrgOrderId' => '202210312A242',
                        'SubMerchantCode' => '',
                        'recur_frequency' => '',
                        'recur_expiry' => '',
                        'CardType' => '',
                        'Lang' => 'tr',
                        'BonusAmount' => '',
                        'InstallmentCount' => '0',
                        'Rnd' => '',
                        'AlphaCode' => 'TL',
                        'Ecommerce' => '1',
                        'MrcCountryCode' => '792',
                        'MrcName' => '3D PAY TEST ISYERI',
                        'MerchantHomeUrl' => 'https://vpostest.qnbfinansbank.com/',
                        'CardHolderName' => '',
                        'IrcDet' => 'Seçili İşlem Bulunamadı!',
                        'IrcCode' => '99961',
                        'Version' => '',
                        'TxnStatus' => 'P',
                        'CavvAlg' => '',
                        'ParesVerified' => '',
                        'ParesSyntaxOk' => '',
                        'ErrMsg' => 'Seçili İşlem Bulunamadı!',
                        'VendorDet' => '',
                        'D3Status' => '-1',
                        'TxnResult' => '',
                        'AuthCode' => '',
                        'HostRefNum' => '',
                        'ProcReturnCode' => 'V013',
                        'ReturnUrl' => '',
                        'ErrorData' => '',
                        'BatchNo' => '4320',
                        'VoidDate' => '',
                        'CardMask' => '',
                        'ReqId' => '26786448',
                        'UsedPoint' => '0',
                        'SrcType' => 'VPO',
                        'RefundedAmount' => '0',
                        'RefundedPoint' => '0',
                        'ReqDate' => '0',
                        'SysDate' => '0',
                        'F11' => '101906',
                        'F37' => '',
                        'IsRepeatTxn' => '',
                        'CavvResult' => '',
                        'VposElapsedTime' => '0',
                        'BankingElapsedTime' => '0',
                        'SocketElapsedTime' => '0',
                        'HsmElapsedTime' => '0',
                        'MpiElapsedTime' => '0',
                        'hasOrderId' => 'True',
                        'TemplateType' => '0',
                        'HasAddressCount' => 'False',
                        'IsPaymentFacilitator' => 'False',
                        'MerchantCountryCode' => '',
                        'OrgTxnType' => '',
                        'F11_ORG' => '0',
                        'F12_ORG' => '0',
                        'F13_ORG' => '',
                        'F22_ORG' => '0',
                        'F25_ORG' => '0',
                        'MTI_ORG' => '0',
                        'DsBrand' => '',
                        'IntervalType' => '0',
                        'IntervalDuration' => '0',
                        'RepeatCount' => '0',
                        'CustomerCode' => '',
                        'RequestMerchantDomain' => '',
                        'RequestClientIp' => '89.244.149.137',
                        'ResponseRnd' => '',
                        'ResponseHash' => '',
                        'BankInternalResponseCode' => '',
                        'BankInternalResponseMessage' => '',
                        'BankInternalResponseSubcode' => '',
                        'BankInternalResponseSubmessage' => '',
                        'BayiKodu' => '',
                        'VoidTime' => '0',
                        'VoidUserCode' => '',
                        'PaymentLinkId' => '0',
                        'ClientId' => '',
                        'IsQRValid' => '',
                        'IsFastValid' => '',
                        'IsQR' => '',
                        'IsFast' => '',
                        'QRRefNo' => '',
                        'FASTGonderenKatilimciKodu' => '',
                        'FASTAlanKatilimciKodu' => '',
                        'FASTReferansNo' => '',
                        'FastGonderenIBAN' => '',
                        'FASTGonderenAdi' => '',
                        'MobileECI' => '',
                        'HubConnId' => '',
                        'WalletData' => '',
                        'Tds2dsTransId' => '',
                        'Is3DHost' => '',
                        'PAYFORFROMXMLREQUEST' => '1',
                        'SESSION_SYSTEM_USER' => '0',
                    ],
                    'expectedData' => [
                        'auth_code' => null,
                        'order_id' => '202210312A242',
                        'org_order_id' => '202210312A242',
                        'proc_return_code' => 'V013',
                        'error_message' => 'Seçili İşlem Bulunamadı!',
                        'ref_ret_num' => null,
                        'order_status' => null,
                        'transaction_type' => 'status',
                        'masked_number' => null,
                        'amount' => null,
                        'currency' => 'TRY',
                        'status' => 'declined',
                        'status_detail' => 'reject',
                    ],
                ],
            ];
    }

    public function cancelTestDataProvider(): array
    {
        return
            [
                'success1' => [
                    'responseData' => [
                        'AuthCode' => 'S05229',
                        'HostRefNum' => '230423103898',
                        'ProcReturnCode' => '00',
                        'TransId' => '20221031D388',
                        'ErrMsg' => 'Onaylandı',
                        'CardHolderName' => '',
                    ],
                    'expectedData' => [
                        'order_id' => '20221031D388',
                        'auth_code' => 'S05229',
                        'ref_ret_num' => '230423103898',
                        'proc_return_code' => '00',
                        'trans_id' => '20221031D388',
                        'error_code' => null,
                        'error_message' => null,
                        'status' => 'approved',
                        'status_detail' => 'approved',
                    ],
                ],
                'fail1' => [
                    'responseData' => [
                        'AuthCode' => '',
                        'HostRefNum' => '230423103927',
                        'ProcReturnCode' => 'V013',
                        'TransId' => '20221031D388',
                        'ErrMsg' => 'Seçili İşlem Bulunamadı!',
                        'CardHolderName' => '',
                    ],
                    'expectedData' => [
                        'order_id' => '20221031D388',
                        'auth_code' => null,
                        'ref_ret_num' => '230423103927',
                        'proc_return_code' => 'V013',
                        'trans_id' => '20221031D388',
                        'error_code' => 'V013',
                        'error_message' => 'Seçili İşlem Bulunamadı!',
                        'status' => 'declined',
                        'status_detail' => 'reject',
                    ],
                ],
            ];
    }

    public function refundTestDataProvider(): array
    {
        return
            [
                'fail1' => [
                    'responseData' => [
                        'AuthCode' => 'S37109',
                        'HostRefNum' => '230423104777',
                        'ProcReturnCode' => 'V014',
                        'TransId' => '20221031714F',
                        'ErrMsg' => 'Bu işlem geri alınamaz, lüften asıl işlemi iptal edin.',
                        'CardHolderName' => '',
                    ],
                    'expectedData' => [
                        'order_id' => '20221031714F',
                        'auth_code' => null,
                        'ref_ret_num' => '230423104777',
                        'proc_return_code' => 'V014',
                        'trans_id' => '20221031714F',
                        'error_code' => 'V014',
                        'error_message' => 'Bu işlem geri alınamaz, lüften asıl işlemi iptal edin.',
                        'status' => 'declined',
                        'status_detail' => 'request_rejected',
                    ],
                ],
            ];
    }
}
